force-app/main/default/objects/Integration_Credentials__c/Integration_Credentials__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store all the integration related credentials in secure encrypted way.</description>
    <label>Integration Credentials</label>
    <nameField>
        <label>Integration Credentials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Credentials__c/fields/Elixir_Active__c.field-meta.xml
<CustomField>
    <fullName>Elixir_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Fields Contains If the Credentials Are Active Or Not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__c/fields/Elixir_VFPAGE_EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>Elixir_VFPAGE_EndPointURL__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Elixir_VFPAGE_EndPointURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Elixir_AuthPaymentTerminalController.cls
/**
 * @description       : 
 * @author            : Ayushmaan Yadav 
 * @Jira Ticket       : 
 * @last modified on  : 02-11-2024
 * @last modified by  : Ayushmaan Yadav 
 * 
 **/ 
public with sharing class Elixir_AuthPaymentTerminalController {
    
    public String token { get; set; }
    public String navigationText { get; set; }
    public String endpointURL { get; set; }

     /**
    * @description Constructor for the Controller.
    * @author Ayushmaan Yadav | 11th Feburary 2024
    * @param None
    * @returns None
    **/
    public Elixir_AuthPaymentTerminalController() {
        // Retrieve the token from the URL parameters
        Integration_Credentials__c cred= [SELECT Elixir_VFPAGE_EndPointURL__c FROM Integration_Credentials__c WHERE Name LIKE 'Authorization Dot Net%' AND Elixir_Active__c = true WITH SECURITY_ENFORCED LIMIT 1];
        token = ApexPages.currentPage().getParameters().get('token');
        Blob decodedBlob;
        try {
            decodedBlob = EncodingUtil.base64Decode(token);
        } catch(Exception e) { 
            system.debug('Error while Decoding the token');
        }
        
		token = decodedBlob.toString();
        navigationText = Label.ElixirRedirectingToPaymentPage;
        endpointURL = cred.Elixir_VFPAGE_EndPointURL__c;
    }

}