force-app/main/default/objects/Integration_Credentials__c/Integration_Credentials__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store all the integration related credentials in secure encrypted way.</description>
    <label>Integration Credentials</label>
    <nameField>
        <label>Integration Credentials Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Credentials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Credentials__c/fields/Elixir_Active__c.field-meta.xml
<CustomField>
    <fullName>Elixir_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Fields Contains If the Credentials Are Active Or Not</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__c/fields/Elixir_Transaction_Key__c.field-meta.xml
<CustomField>
    <fullName>Elixir_Transaction_Key__c</fullName>
    <label>Transaction Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__c/fields/EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>EndPointURL__c</fullName>
    <description>This field will hold the endpoint URL.</description>
    <label>EndPointURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Integration_Credentials__c/fields/Integration_Key__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key__c</fullName>
    <description>This field will store the value for the facility ID.</description>
    <label>Integration Key</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/Elixir_AuthorizeCallout.cls
/**
 * @description       : 
 * @author            : Ayushmaan Yadav 
 * @Jira Ticket       : 
 * @last modified on  : 02-11-2024
 * @last modified by  : Ayushmaan Yadav 
 * 
 **/ 
public with sharing class Elixir_AuthorizeCallout {

    
    private static final String RESPONSE = 'Response';
    private static final String REQUEST = 'Request';
    private Integration_Credentials__c  integrationCreds;

    /**
    * @description Constructer of the Class
    * @author Ayushmaan Yadav | 11th Feburary 2024
    * @param None 
    * @returns None
    **/
    public Elixir_AuthorizeCallout() {
        List<Integration_Credentials__c> credList= [SELECT EndPointURL__c,Integration_Key__c,Elixir_Transaction_Key__c FROM Integration_Credentials__c WHERE Name LIKE 'Authorization Dot Net%' AND Elixir_Active__c = true WITH SECURITY_ENFORCED LIMIT 1];
        if (credList.size() > 0){
            integrationCreds = credList[0];
        }
    }

    /**
    * @description Get API key for authorize.net
    * @author Ayushmaan Yadav | 11th Feburary 2024
    * @param None
    * @returns String
    **/
    public String getAPIKey(){
        return integrationCreds != null ? integrationCreds.Integration_Key__c : null;
    }

    /**
    * @description Get Transaction key for authorize.net
    * @author Ayushmaan Yadav | 11th Feburary 2024
    * @param None
    * @returns String
    **/
    public String getTransactionKey(){
        return integrationCreds != null ? integrationCreds.Elixir_Transaction_Key__c : null;
    }

    /**
    * @description Send and Create Http Request
    * @author Ayushmaan Yadav | 11th Feburary 2024
    * @param String requestJson
    * @returns HttpResponse
    **/
    public HttpResponse sendRequest(String requestJson) {

        Http http = new Http();
        HttpResponse httpRes;

        HttpRequest req = createHttpReq(requestJson);
        try {
            httpRes = http.send(req);
            Elixir_LogUtility.logResponse(requestJson,httpRes.getBody());
            if (httpRes.getStatusCode() == 200) {
                // Handle Successful Response Here
                System.debug('Successful Response');
            } else if (httpRes.getStatusCode() >=400 && httpRes.getStatusCode() <= 499) {
                // Handle 400 Series Codes   
                System.debug('400 Series Codes');
            } else if (httpRes.getStatusCode() >=500 && httpRes.getStatusCode() <= 599) {
                // Handle 500 Series Codes 
                System.debug('500 Series Codes');
            } else {
                // Handle Other Status Code
                System.debug('Other Status Code');
            }
        } catch (Exception e) {
            // Log Response in case of Exception 
            Elixir_LogUtility.logResponse(requestJson,e.getStackTraceString());
        }
        
        return httpRes;
    }
    
    /**
    * @description Create Http Request and Add the Required Data 
    * @author Ayushmaan Yadav | 11th Feburary 2024
    * @param None
    * @returns HttpRequest
    **/
    private HttpRequest createHttpReq(String requestJson) {
        HttpRequest req = new  HttpRequest();
        req.setEndpoint(integrationCreds.EndPointURL__c);
        req.setBody(requestJson);
        req.setMethod('POST');
        return req;
    }

}